/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNavbar: typeof import('./src/components/AppNavbar.vue')['default']
    ImageNodeView: typeof import('./src/components/editor/ImageNodeView.vue')['default']
    MainView: typeof import('./src/views/MainView.vue')['default']
    NotebookTree: typeof import('./src/components/sidebar/NotebookTree.vue')['default']
    NotebookTreeItem: typeof import('./src/components/sidebar/NotebookTreeItem.vue')['default']
    NoteEditor: typeof import('./src/components/editor/NoteEditor.vue')['default']
    NoteList: typeof import('./src/components/notelist/NoteList.vue')['default']
    NoteListItem: typeof import('./src/components/notelist/NoteListItem.vue')['default']
    SearchModal: typeof import('./src/components/search/SearchModal.vue')['default']
    SettingsView: typeof import('./src/views/SettingsView.vue')['default']
    SidebarActions: typeof import('./src/components/sidebar/SidebarActions.vue')['default']
    UnlockView: typeof import('./src/views/UnlockView.vue')['default']
  }
}
