/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FirstComponent: typeof import('./src/components/FirstComponent.vue')['default']
    FisrtComponent: typeof import('./src/components/FisrtComponent.vue')['default']
  }
}
